version: "3.4"
services:
  ui:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BASE_URL=http://207.148.69.21:8888
  api:
    build: ./server
    ports:
      - "8888:8888"
    environment:
      - PORT=8888
      - MONGO_URI=mongodb+srv://test:test@cluster0.qsrxo.mongodb.net/oddandeven?retryWrites=true&w=majority
      - ACCESS_TOKEN_SECRET_KEY=somerandomstring
      - JWT_ACCESS_TOKEN_LIFE=14d
      - THE_SIEU_RE_URL=https://api.dailysieure.com/api-tsr/?taikhoan=nrowin&matkhau=0388760127t1
      - MOMO_URL=https://api.web2m.com/historyapimomo/E9565811-67A5-5422-FC40-C40BCDF292DB
