export const BET_TYPES = {
  EVENODDHIGHLOW: "EVENODDHIGHLOW",
  XIEN: "XIEN",
  LO: "LO",
};

export const EVENODDHIGHLOW_OPTIONS = {
  EVEN: "EVEN",
  ODD: "ODD",
  HIGH: "HIGH",
  LOW: "LOW",
};

export const XIEN_OPTIONS = {
  ODDHIGH: "ODDHIGH",
  ODDLOW: "ODDLOW",
  EVENHIGH: "EVENHIGH",
  EVENLOW: "EVENLOW",
};
